version: '3.7'

services:
  sports-stats-web-service:
    build: .
    image: sports-stats-web-service:latest
    container_name: sports-stats-service
    environment:
      - VERSION=0.0.5
      - PORT=5000
    ports:
      - 5000:5000
    restart: always
